Remove PSP patch from giantswarm flux-app (#255)
This PR:

- removes the patch for the `flux-app-pvc-psp` PSP as the PSP is no
longer used.

This patch is causing all `mc-bootstrap` runs to fail (see an example
[here](https://tekton.ci.giantswarm.io/#/namespaces/mc-bootstrap/pipelineruns/daily-recreation-goshawk-7fdgv?pipelineTask=generate-mc&step=generate-mc)).

This is the exact error:

```
Error: no resource matches strategic merge patch "PodSecurityPolicy.v1beta1.policy/flux-app-pvc-psp.flux-giantswarm": no matches for Id PodSecurityPolicy.v1beta1.policy/flux-app-pvc-psp.flux-giantswarm; failed to find unique target for patch PodSecurityPolicy.v1beta1.policy/flux-app-pvc-psp.flux-giantswarm
```